version: '3.8'

services:
  app:
    build: .
    container_name: invite-code-system
    restart: always
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.docker
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 